[settings]
hotkey = "Alt+Backquote"
refresh_interval_secs = 5
start_minimized = true

[[projects]]
id = "proj_red_mozbqhsk"
name = "RED"
uproject_path = 'I:\RED\LetsGoDevelop\LetsGo\RED.uproject'
working_dir = 'I:\RED\LetsGoDevelop\LetsGo'
default_args = ""
default_map = ""
default_port = 7777
log_dir = 'I:\RED\LetsGoDevelop\LetsGo/Saved/Logs'
icon_color = "#00E5FF"
tags = []

[[history]]
id = "h_30442b2a903f4f3db95b2c45f26a6849"
project_id = "proj_red_mozbqhsk"
mode = "Editor"
map = ""
port = 0
extra_args = "-skipcompile -map=/Game/Feature/RED/Levels/RuntimeLevels/Outside/AncientTown/AncientTown_Main -server -log -nosteam -port=17777 -ds_game_type=121 -localds=71001 -startmode=1 -CustomMatchType=71001 -LOG=DSRED.log  \"-mwtitle=RED Local DS 71001 AncientTown_Main\" "
log_file = ""
working_dir = 'I:\RED\LetsGoDevelop\LetsGo'
launch_count = 10
last_used_at = 1778474060
created_at = 1778439445
pinned = false
label = "DS71001"

[history.env]

[[history]]
id = "h_39ea7e63cf684434871478cc8a4878c0"
project_id = "proj_red_mozbqhsk"
mode = "Editor"
map = ""
port = 0
extra_args = ""
log_file = ""
working_dir = 'I:\RED\LetsGoDevelop\LetsGo'
launch_count = 5
last_used_at = 1778480707
created_at = 1778440518
pinned = false
label = "Editor"

[history.env]
